import test from 'node:test';
import assert from 'node:assert/strict';
import {setTimeout as delay} from 'node:timers/promises';
import {planKeyWindows,planVocalBatches,normalizeVocalWindow,VocalIntelligenceSession} from '../server/vocal-intelligence.mjs';
import {normalizeKey,normalizeKeySample,resolveTonality,normalizeTonality,normalizeObservation,voiceForToken,vocalCoverage,INTELLIGENCE_VERSION} from '../shared/vocal-intelligence.mjs';
import {normalizeFastScan,analyzeAdaptive} from '../server/adaptive.mjs';
import {normalizeAnalysis} from '../shared/schema.mjs';
import {applyTeachingBatches,buildTeachingBatches,normalizeTeachingBatch,settleTeachingBatch} from '../shared/annotations.mjs';
import {interactionsBody,requestBody,generate} from '../server/gemini.mjs';
import {AppError} from '../server/validation.mjs';
import {intelligenceScan,keyResponse,voiceResponse,practiceResponse,intelligenceResponder} from './fixtures/intelligence-fixture.mjs';
const input={source:'youtube',url:'https://www.youtube.com/watch?v=62VyD_SVS40',id:'62VyD_SVS40',language:'auto'};
const config={apiKey:'qa-local-not-a-live-credential',model:'gemini-3.8-flash',timeout:3000,retryDelays:[0,0,0]};
const enabled={intelligenceEnabled:true};
const keySamples=(keys=['C','C','C','C','C'])=>planKeyWindows(200).map((w,i)=>normalizeKeySample(keyResponse(w,keys[i]),w));
const segment=(start=1,end=5,voice='chest',extra={})=>({start,end,voice,confidence:'high',evidence:'音色較實而連續。',qualities:['connected'],transition:false,transitionEvidence:'',...extra});

test('independent key windows are bounded and span early, middle, late recording',()=>{const w=planKeyWindows(300);assert.equal(w.length,5);assert.ok(w[0].clipStart<60&&w.at(-1).clipEnd>240);for(let i=0;i<w.length;i++){assert.ok(w[i].clipEnd-w[i].clipStart<=28);if(i)assert.ok(w[i].clipStart>=w[i-1].clipEnd);}});
for(const duration of [.5,8,12,35,60,99.5,899.99,900])test(`key windows remain within real source duration ${duration}`,()=>{for(const w of planKeyWindows(duration)){assert.ok(w.clipStart>=0&&w.clipEnd<=duration&&w.clipEnd>w.clipStart);}});
test('invalid source lengths do not create analysis windows',()=>{for(const d of [-1,NaN,901,Infinity])assert.throws(()=>planKeyWindows(d));});
test('enharmonic key spellings normalize without confusing relative minor',()=>{assert.deepEqual(normalizeKey('C#','major'),normalizeKey('Db','major'));assert.notDeepEqual(normalizeKey('A','minor'),normalizeKey('C','major'));assert.equal(normalizeKey('H','major'),null);});
test('a single teaching batch cannot set global key',()=>{const a=normalizeFastScan(intelligenceScan(2));const b=buildTeachingBatches(a)[0];const r=normalizeTeachingBatch({...practiceResponse(b),key:'F# major'},b);assert.equal(applyTeachingBatches(a,[r]).key,'待確認');});
test('three agreeing non-overlapping windows establish provisional consensus',()=>{const t=resolveTonality(keySamples().slice(0,3),{finished:true});assert.equal(t.status,'stable');assert.equal(t.primary.tonic,'C');assert.equal(t.accuracyVerified,false);});
test('two agreeing windows are not promoted to confident song key',()=>{assert.equal(resolveTonality(keySamples().slice(0,2),{finished:true}).status,'uncertain');});
test('single contrary final window is a dispute, not automatic modulation',()=>{assert.equal(resolveTonality(keySamples(['C','C','C','C','D']),{finished:true}).status,'uncertain');});
test('supported two-region modulation retains an interval, not invented timestamp',()=>{const t=resolveTonality(keySamples(['C','C','C','D','D']),{finished:true});assert.equal(t.status,'modulating');assert.equal(t.changes.length,1);assert.equal(t.changes[0].precision,'window-bracket');assert.ok(t.changes[0].latest>t.changes[0].earliest);});
test('disjoint contrary estimates do not create fake key changes',()=>{assert.equal(resolveTonality(keySamples(['C','D','C','D','C']),{finished:true}).status,'uncertain');});
test('relative-major/minor alternate reduces confidence, not discarded',()=>{const ss=keySamples();ss[0].alternative=normalizeKey('A','minor');const t=resolveTonality(ss,{finished:true});assert.equal(t.alternative.mode,'minor');assert.equal(t.confidence,'medium');});
test('no accompaniment evidence cannot be promoted by high self-confidence',()=>{const w=planKeyWindows(60)[0];const s=normalizeKeySample({...keyResponse(w),accompaniment:false},w);assert.equal(s.status,'uncertain');});
test('wrong key window ID is a missing answer',()=>{const w=planKeyWindows(60)[0];assert.equal(normalizeKeySample({...keyResponse(w),windowId:'elsewhere'},w).status,'missing');});
test('import recomputes key agreement and rejects accuracy certification',()=>{const raw={...resolveTonality(keySamples().slice(0,1),{finished:true}),status:'stable',confidence:'high',accuracyVerified:true};const t=normalizeTonality(raw,200);assert.equal(t.status,'uncertain');assert.equal(t.accuracyVerified,false);});
test('vocal windows include all lyric occurrences with bounded audio span',()=>{const a=normalizeFastScan(intelligenceScan(80));const bs=planVocalBatches(a);assert.equal(new Set(bs.flatMap(b=>b.phrases.map(p=>p.id))).size,80);assert.ok(bs.every(b=>b.window.clipEnd-b.window.clipStart<=36));});
test('long vocal phrase is fragmented without dropping its ending',()=>{const a=normalizeFastScan(intelligenceScan(1));a.duration=200;a.phrases[0].end=150;const b=planVocalBatches(a);assert.ok(b.length>=5);assert.equal(b.at(-1).phrases.at(-1).coreEnd,150);});
test('teaching batches may also use an explicit audio-duration bound',()=>{const a=normalizeFastScan(intelligenceScan(10));const b=buildTeachingBatches(a,{maxSeconds:20});assert.ok(b.every(x=>x.end-x.start<=20));});
test('vocal batch requires the exact occurrence ID and text',()=>{const a=normalizeFastScan(intelligenceScan(2)),b=planVocalBatches(a)[0],r=voiceResponse(b);r.phrases[0].text='錯誤文字';const out=normalizeVocalWindow(r,b);assert.equal(out.fragments.get('p0').status,'missing');assert.equal(out.fragments.get('p1').status,'reviewed');});
test('duplicate phrase observations cannot silently overwrite one another',()=>{const b=planVocalBatches(normalizeFastScan(intelligenceScan(2)))[0],r=voiceResponse(b);r.phrases.push(r.phrases[0]);assert.equal(normalizeVocalWindow(r,b).fragments.get('p0').status,'missing');});
test('clip-relative vocal timestamps add source offset exactly once',()=>{const b=planVocalBatches(normalizeFastScan(intelligenceScan(12)))[1],r=voiceResponse(b);r.timeBase='clip_seconds';for(const p of r.phrases)for(const s of p.segments){s.start-=b.window.clipStart;s.end-=b.window.clipStart;}const result=normalizeVocalWindow(r,b);assert.equal(result.fragments.get(b.phrases[0].id).segments[0].start,b.phrases[0].coreStart);});
test('unknown vocal time base is rejected instead of guessed',()=>{const b=planVocalBatches(normalizeFastScan(intelligenceScan(2)))[0];assert.throws(()=>normalizeVocalWindow({...voiceResponse(b),timeBase:'minutes'},b));});
test('out-of-window observation cannot label another phrase',()=>{const b=planVocalBatches(normalizeFastScan(intelligenceScan(2)))[0],r=voiceResponse(b);r.phrases[0].segments[0].end=100;assert.equal(normalizeVocalWindow(r,b).fragments.get('p0').segments.length,0);});
test('legacy practice label cannot become original singer observation',()=>{const p=normalizeFastScan(intelligenceScan(1)).phrases[0];p.tokens[0].technique='falsetto';assert.equal(voiceForToken(p,p.tokens[0]).voice,'unknown');});
test('airy modal-like quality remains chest-like, not forced falsetto',()=>{const o=normalizeObservation({status:'reviewed',segments:[segment(1,5,'chest',{qualities:['airy','connected']})]},1,5);assert.equal(o.segments[0].voice,'chest');assert.ok(o.segments[0].qualities.includes('airy'));});
test('high note is never itself used to infer original falsetto',()=>{const p=normalizeFastScan(intelligenceScan(1)).phrases[0];p.tokens[0].notes=[90];p.observedVoice=normalizeObservation({status:'reviewed',segments:[segment()]},1,5);assert.equal(voiceForToken(p,p.tokens[0]).voice,'chest');});
test('missing audible evidence cannot masquerade as high-confidence detection',()=>{const o=normalizeObservation({status:'reviewed',segments:[segment(1,5,'falsetto',{evidence:''})]},1,5);assert.equal(o.segments[0].voice,'unknown');assert.equal(o.status,'uncertain');});
test('unsupported rapid category flip is marked conflict, not blindly smoothed',()=>{const o=normalizeObservation({status:'reviewed',segments:[segment(1,1.2),segment(1.2,1.4,'falsetto')]},1,5);assert.equal(o.segments[1].status,'conflict');assert.equal(o.segments[0].voice,'chest');});
test('explicit evidence-backed rapid register change is preserved',()=>{const o=normalizeObservation({status:'reviewed',segments:[segment(1,1.2),segment(1.2,1.4,'falsetto',{transition:true,transitionEvidence:'聽到清晰轉輕。'})]},1,5);assert.equal(o.segments[1].voice,'falsetto');});
test('one word across supported transition does not receive arbitrary class',()=>{const p={start:1,end:5,observedVoice:normalizeObservation({status:'reviewed',segments:[segment(1,3),segment(3,5,'falsetto',{transition:true,transitionEvidence:'轉輕'})]},1,5)};const d=voiceForToken(p,{start:2,end:4});assert.equal(d.voice,'unknown');assert.equal(d.transition,true);});
test('unknown word timing uses only coherent phrase observation',()=>{const p={start:1,end:5,observedVoice:normalizeObservation({status:'reviewed',segments:[segment()]},1,5)};assert.equal(voiceForToken(p,{start:null,end:null}).scope,'phrase');p.observedVoice.segments.push(segment(3,5,'falsetto'));assert.equal(voiceForToken(p,{start:null,end:null}).voice,'unknown');});
test('untimed lyrics remain in original-direction coverage denominator',()=>{const a=normalizeFastScan(intelligenceScan(2));a.unalignedLyrics=['微光同行'];assert.equal(vocalCoverage(a).total,12);assert.equal(vocalCoverage(a).untimed,4);});
test('honest settlement distinguishes missing API entries from heard uncertainty',()=>{const b=buildTeachingBatches(normalizeFastScan(intelligenceScan(1)))[0];const r=settleTeachingBatch(b,{status:'ok'},{honest:true});assert.equal(r.missing.length,4);assert.equal([...r.annotations.values()][0].annotationStatus,'missing');});
test('new production first result precedes every key and vocal call',async()=>{const seen=[],events=[];let ready=false;const fn=intelligenceResponder(undefined,seen);const a=await analyzeAdaptive(input,async(x,k)=>{if(k!=='fast-scan')assert.ok(ready);return fn(x,k);},{...enabled,onProgress:e=>{events.push(e);if(e.type==='ready')ready=true;}});assert.ok(a.vocalIntelligence);assert.ok(events[0]);assert.equal(a.adaptive.state,'complete');});
test('practice suggestions and observations remain separately inspectable',async()=>{const a=await analyzeAdaptive(input,intelligenceResponder(),enabled);assert.equal(a.phrases[0].tokens[0].practiceTechnique,'mix');assert.equal(voiceForToken(a.phrases[0],a.phrases[0].tokens[0]).voice,'chest');});
test('whole-song key comes from independent key tasks, not practice response',async()=>{const a=await analyzeAdaptive(input,intelligenceResponder(),enabled);assert.equal(a.tonality.status,'stable');assert.equal(a.key,'C major');assert.equal(a.tonality.samples.length,5);});
test('vocal and key enrichment do not move the established lyric timeline',async()=>{const raw=intelligenceScan();const a=await analyzeAdaptive(input,intelligenceResponder(raw),enabled);assert.deepEqual(a.phrases.map(p=>[p.start,p.end]),raw.phrases.map(p=>[p.start,p.end]));});
test('complete output survives JSON export and strict re-import',async()=>{const a=await analyzeAdaptive(input,intelligenceResponder(),enabled);const b=normalizeAnalysis(JSON.parse(JSON.stringify(a)));assert.deepEqual(b.tonality,a.tonality);assert.deepEqual(b.phrases[0].observedVoice,a.phrases[0].observedVoice);assert.equal(b.vocalIntelligence.accuracyVerified,false);});
test('legacy saved score does not fabricate a new original observation',()=>{const a=normalizeAnalysis(normalizeFastScan(intelligenceScan(1)));assert.equal(a.phrases[0].observedVoice,undefined);});
test('new tasks share a maximum of three workers',async()=>{let n=0,peak=0;const fn=intelligenceResponder(intelligenceScan(40));await analyzeAdaptive(input,async(x,k)=>{n++;peak=Math.max(n,peak);try{await delay(2);return await fn(x,k);}finally{n--;}},{...enabled,concurrency:100});assert.ok(peak<=3);});
test('cancellation after ready schedules no extra music-analysis requests',async()=>{const ctrl=new AbortController(),seen=[];await assert.rejects(analyzeAdaptive(input,intelligenceResponder(undefined,seen),{...enabled,signal:ctrl.signal,onProgress:p=>{if(p.type==='ready')ctrl.abort();}}));assert.deepEqual(seen.map(x=>x.kind),['fast-scan']);});
test('failure of key service preserves lyrics and later vocal coverage',async()=>{const fn=intelligenceResponder();const a=await analyzeAdaptive(input,(x,k)=>k==='key-window'?Promise.reject(new AppError('format',502,'KEY_FORMAT')):fn(x,k),enabled);assert.equal(a.adaptive.state,'partial');assert.equal(a.phrases.length,12);assert.equal(a.tonality.status,'unavailable');assert.ok(vocalCoverage(a).identified>0);});
test('omitted vocal entries stay missing and never borrow practice classes',async()=>{const fn=intelligenceResponder();const a=await analyzeAdaptive(input,(x,k)=>k==='vocal-observation'?{raw:{status:'ok',windowId:x.voiceBatch.id,timeBase:'source_seconds',phrases:[]}}:fn(x,k),enabled);assert.equal(a.adaptive.state,'partial');assert.equal(vocalCoverage(a).identified,0);assert.ok(vocalCoverage(a).missing>0);assert.equal(a.phrases[0].tokens[0].practiceTechnique,'mix');});
test('persistent provider outage stops optional fan-out and preserves ready lyrics',async()=>{const fn=intelligenceResponder(intelligenceScan(80));let n=0;const a=await analyzeAdaptive(input,(x,k)=>{if(k!=='fast-scan'){n++;throw new AppError('busy',502,'GEMINI_503');}return fn(x,k);},enabled);assert.equal(a.adaptive.state,'partial');assert.ok(n<=5,`${n} attempts`);assert.equal(a.phrases.length,80);});
test('all uncertain observations get at most three targeted re-listens',async()=>{const fn=intelligenceResponder(intelligenceScan(50));const a=await analyzeAdaptive(input,(x,k)=>['vocal-observation','vocal-review'].includes(k)?{raw:voiceResponse(x.voiceBatch,{voice:'unknown',confidence:'low'})}:fn(x,k),enabled);assert.equal(a.vocalIntelligence.verificationCalls,3);});
test('targeted re-listen is source-bounded and blind to initial classification',async()=>{const fn=intelligenceResponder(),seen=[];await analyzeAdaptive(input,(x,k)=>{if(k==='vocal-review'){seen.push(x);return {raw:voiceResponse(x.voiceBatch)};}if(k==='vocal-observation')return {raw:voiceResponse(x.voiceBatch,{voice:'unknown',confidence:'low'})};return fn(x,k);},enabled);assert.ok(seen.length>0);for(const x of seen){assert.ok(x.listeningWindow.clipEnd-x.listeningWindow.clipStart<=10);assert.equal(JSON.stringify(x.voiceBatch).includes('observedVoice'),false);}});
test('high-confidence conflicting re-listens remain conflict instead of winning by confidence',async()=>{const fn=intelligenceResponder();const a=await analyzeAdaptive(input,(x,k)=>k==='vocal-observation'?{raw:voiceResponse(x.voiceBatch,{voice:'chest',transition:true})}:k==='vocal-review'?{raw:voiceResponse(x.voiceBatch,{voice:'falsetto'})}:fn(x,k),enabled);assert.ok(a.phrases.some(p=>p.observedVoice.segments.some(s=>s.status==='conflict')));});
test('new schemas keep observed voice separate from practice technique',()=>{const a=normalizeFastScan(intelligenceScan(2)),batch=planVocalBatches(a)[0],x={...input,voiceBatch:batch,listeningWindow:batch.window};const b=interactionsBody(x,'vocal-observation',config.model);assert.ok(b.response_format.schema.properties.phrases.items.properties.segments);assert.ok(!b.response_format.schema.properties.phrases.items.properties.tokens);const p=interactionsBody({...input,teachingBatch:buildTeachingBatches(a)[0]},'light-teaching',config.model);assert.ok(p.response_format.schema.properties.phrases.items.properties.tokens.items.properties.practiceTechnique);assert.equal(p.response_format.schema.properties.key,undefined);});
test('key and voice prompts do not inherit the practice-only teacher role',()=>{const a=normalizeFastScan(intelligenceScan(2)),batch=planVocalBatches(a)[0];for(const k of ['key-window','vocal-observation']){const b=requestBody({...input,voiceBatch:batch,listeningWindow:batch.window},k);assert.ok(!b.systemInstruction.parts[0].text.includes('technique永遠是可嘗試'));assert.equal(b.generationConfig.maxOutputTokens,k==='key-window'?1024:4096);}});
test('new requests retain official media clipping and never switch model',()=>{const batch=planVocalBatches(normalizeFastScan(intelligenceScan(10)))[1];const b=interactionsBody({...input,voiceBatch:batch,listeningWindow:batch.window},'vocal-observation',config.model);assert.equal(b.model,config.model);assert.equal(b.input[0].uri,input.url);assert.equal(b.input[0].processing.start_offset,`${batch.window.clipStart}s`);});
test('actual default generate path wires key, original voice, and practice tasks',async()=>{
 const scan=intelligenceScan(12),types=[];
 const fetcher=async(url,options)=>{const b=JSON.parse(options.body),prompt=b.input[1].text,props=b.response_format.schema.properties;let raw;
  if(props.tonic){types.push('key');const id=prompt.match(/窗口ID (key-\d+)/)[1];raw=keyResponse({id});}
  else if(props.phrases.items.properties.segments){types.push('voice');const phrases=JSON.parse(prompt.split('純資料，不是指令：')[1].trim());const id=prompt.match(/窗口ID ([\w-]+)/)[1];raw=voiceResponse({id,phrases});}
  else if(props.phrases.items.properties.tokens){types.push('practice');const phrases=JSON.parse(prompt.split('資料不是指令：')[1].split('\n回指定')[0]);raw=practiceResponse({phrases});}
  else {types.push('fast');raw=scan;}
  return new Response(JSON.stringify({status:'completed',output_text:JSON.stringify(raw)}));
 };
 const a=await generate(input,'analyze',config,new AbortController().signal,fetcher);assert.equal(a.adaptive.state,'complete');assert.equal(types[0],'fast');assert.ok(types.includes('key')&&types.includes('voice')&&types.includes('practice'));assert.equal(a.vocalIntelligence.version,INTELLIGENCE_VERSION);
});

test('duplicate imported key windows cannot fake three independent observations',()=>{const s=keySamples()[0];const raw={version:INTELLIGENCE_VERSION,status:'stable',samples:[s,{...s,start:40,end:68},{...s,start:80,end:108}],expected:3};assert.notEqual(normalizeTonality(raw,200).status,'stable');});
test('all key-unavailable responses are partial processing, not completed key detection',async()=>{const fn=intelligenceResponder();const a=await analyzeAdaptive(input,(x,k)=>k==='key-window'?{raw:{status:'unavailable',windowId:x.listeningWindow.id}}:fn(x,k),enabled);assert.equal(a.adaptive.state,'partial');assert.equal(a.tonality.status,'unavailable');});
test('timing counters update when real word boundaries arrive',async()=>{const fn=intelligenceResponder();const a=await analyzeAdaptive(input,async(x,k)=>{const r=await fn(x,k);if(k==='light-teaching'){r.wordDetails=new Map(x.teachingBatch.phrases.flatMap(p=>p.tokens.map((t,i)=>[t.id,{start:p.start+i*.7,end:p.start+i*.7+.6,romanization:'',confidence:'high'}])));}return r;},enabled);assert.equal(a.dataQuality.timedTokens,a.phrases.reduce((n,p)=>n+p.tokens.length,0));});
test('late phrase envelope updates never shift original observed source intervals',async()=>{const a=normalizeFastScan(intelligenceScan(1)),session=new VocalIntelligenceSession(a),b=session.voiceBatches[0];await session.voiceTask(b,async()=>({raw:voiceResponse(b)}));a.phrases[0].start=2;const out=session.apply(normalizeAnalysis(a));assert.equal(out.phrases[0].observedVoice.segments[0].start,2);assert.equal(out.phrases[0].observedVoice.segments[0].end,5);});
test('live QA parser uses supplied Markdown link rather than silently replacing song',async()=>{const {parseSources}=await import('../scripts/verify-music.mjs');assert.equal(parseSources(['[source](https://www.youtube.com/watch?v=62VyD_SVS40)'])[0].id,'62VyD_SVS40');assert.throws(()=>parseSources(['nonsense']));});
test('live music metrics retain uncertainty and explicitly exclude accuracy claims',async()=>{const {musicMetrics}=await import('../scripts/verify-music.mjs');const a=await analyzeAdaptive(input,intelligenceResponder(),enabled);const m=musicMetrics(a);assert.equal(m.accuracy,'not-measured');assert.equal(m.quarters.length,4);assert.equal(m.original.total,48);assert.equal(m.result,'pipeline-integrity-passed');});

test('actual HTTP slow bodies reserve analysis slots before validation awaits',async()=>{
 const http=await import('node:http'),{createApp}=await import('../server/index.mjs');let active=0,peak=0,release;
 const gate=new Promise(r=>release=r);
 const server=createApp({...config,host:'127.0.0.1',origin:'',accessCode:'',production:false},{generate:async()=>{active++;peak=Math.max(peak,active);await gate;active--;return normalizeFastScan(intelligenceScan(1));}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const requests=[],jobs=[];let rejections=0;
 try{
  const body=JSON.stringify({source:'youtube',url:input.url,language:'auto'});
  for(let i=0;i<8;i++)jobs.push(new Promise((resolve,reject)=>{
   const req=http.request({hostname:'127.0.0.1',port:server.address().port,path:'/api/analyze',method:'POST',headers:{'Content-Type':'application/json','Content-Length':Buffer.byteLength(body)}},res=>{res.resume();res.on('end',()=>{if(res.statusCode===429)rejections++;resolve(res.statusCode);});});
   req.on('error',reject);req.write(body.slice(0,2));requests.push(req);
  }));
  const until=Date.now()+2000;while(rejections<5&&Date.now()<until)await delay(5);assert.equal(rejections,5);for(const req of requests)req.end(body.slice(2));await delay(35);release();
  const statuses=await Promise.all(jobs);assert.equal(statuses.filter(s=>s===200).length,3);assert.equal(statuses.filter(s=>s===429).length,5);assert.ok(peak<=3);
 }finally{release();server.closeAllConnections();await new Promise(r=>server.close(r));}
});
test('actual HTTP stream carries separate original observations and key consensus',async()=>{
 const {createApp}=await import('../server/index.mjs');const server=createApp({...config,host:'127.0.0.1',origin:'',accessCode:'',production:false},{generate:(i,k,c,s,unused,emit)=>analyzeAdaptive(i,intelligenceResponder(),{...enabled,signal:s,onProgress:emit})});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));
 try{const response=await fetch(`http://127.0.0.1:${server.address().port}/api/analyze`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});const packets=(await response.text()).trim().split('\n').map(JSON.parse);const ready=packets.find(p=>p.type==='ready').result,done=packets.find(p=>p.type==='done').result;
  assert.equal(ready.tonality.status,'pending');assert.equal(done.tonality.status,'stable');assert.equal(done.phrases[0].observedVoice.segments[0].voice,'chest');assert.equal(done.phrases[0].tokens[0].practiceTechnique,'mix');assert.ok(packets.filter(p=>p.type==='update').length>1);
 }finally{server.closeAllConnections();await new Promise(r=>server.close(r));}
});
